version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t dockerpy .
      - docker tag dockerpy:latest 077277174591.dkr.ecr.ap-southeast-1.amazonaws.com/dockerpy:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 077277174591.dkr.ecr.ap-southeast-1.amazonaws.com/dockerpy:latest
